language: php
php:
  - 5.5
  - 5.4

env:
  - DB=mysql

services: mysql
before_script:
    - composer install --dev --prefer-source
    - sh tests/setup_$DB.sh

script: ./vendor/bin/phpunit --configuration tests/phpunit_$DB.xml
