<?php
// This thing here will install the development snapshot of Silex to your machine

$success = '';
$error = '';

function randomString($length = 32, $pool = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!?@(){}[]\/=~$%&#*-+.,_') {
	$result = '';
	for($i = 0; $i < $length; $i++)
		$result .= $pool{rand(0, strlen($pool) - 1)};
	return $result;
}

if(file_exists('lib/config.inc.php')) {
		$success = 'Your config file already exists.';
		$error = 'Go away!';
} else if(isset($_POST['install'])) {
	$pdo = null;
	try {
		$pdo = new PDO('mysql:host='.$_POST['host'].';port='.$_POST['port'].';dbname='.$_POST['database'].';', $_POST['user'], $_POST['password'], [PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8']);
		$pdo->query(file_get_contents('docs/silex.sql'));

		//$salt = randomString();
		// default salt, shouldn't be removed until users work properly in Silex
		$salt = '!f~)pzhtU=&=GtVV7Y&u4wp=3A2xB*_,';

		$config = '<?php
// This file was generated by the Silex installer
return [
\'database.host\'     => \''.$_POST['host'].'\',
\'database.user\'     => \''.$_POST['user'].'\',
\'database.password\' => \''.$_POST['password'].'\',
\'database.name\'     => \''.$_POST['database'].'\',
\'database.port\'     => '.$_POST['port'].',
\'database.wrapper\'  => \''.$_POST['type'].'\',
\'password.salt\'     => \''.$salt.'\'
];
';
		file_put_contents('lib/config.inc.php', $config);

		$success = 'Silex was successful configured.';
	} catch (Exception $e) {
		$error = $e->getMessage();
	}
}
?><!DOCTYPE html>
<html>
<head>
	<title>Silex development snapshot installer</title>
	<style type="text/css">
		html,body{font-family:Helvetica, "Droid Sans", "Trebuchet MS", Arial, sans-serif;color:#333;margin:0;padding:0}header{font-size:32px;font-weight:700;line-height:45px;margin-bottom:20px;background:#292c34;color:#fff;text-align:center;padding:10px}header svg{margin-bottom:-10px}header .subtitle{display:inline-block;padding-left:20px;font-size:24px;font-weight:400}table{border:0;border-spacing:0;width:500px;margin:0;padding:0}td{padding-bottom:6px}td:first-child{width:150px}td input,td select{width:100%;height:26px;box-sizing:border-box;border:1px solid #999;outline:0;margin:0;padding:2px}td[colspan="2"] input,td[colspan="2"] select{width:350px;border-radius:2px}td:nth-child(2):not(:last-child) input{border-radius:2px 0 0 2px}td:last-child:not([colspan="2"]){width:60px}td:last-child:not([colspan="2"]) input{border-radius:0 2px 2px 0}.content{width:500px;margin:0 auto;padding:10px}input[type=submit]{cursor:pointer;box-sizing:border-box;border:0;background:#4387fd;width:500px;border-radius:2px;color:#fff;font-weight:700;font-size:20px;text-shadow:0 0 3px rgba(0,0,0,.2);padding:10px}h1{font-size:26px;text-align:center}small{display:block}footer{font-size:10px;text-align:center}.error{background:#ffd5d5;padding:10px;color:#555;font-weight:bold;text-align:center;}
	</style>
</head>
<body>
	<header>
		<svg version="1.1" width="45" height="45" id="silex_logo_single"><path d="M 22.5,0 C 15.178827,0 7.8606446,1.5749 4.7163868,4.7191 c -6.2885157,6.2881 -6.2885157,29.2767 0,35.5649 6.2885152,6.288 29.2787112,6.288 35.5672262,0 6.288516,-6.2882 6.288516,-29.2768 0,-35.5649 C 37.139355,1.5749 29.821173,0 22.5,0 z m 0.90637,6.0317 c 1.80046,0.044 3.575716,0.2254 5.219444,0.5313 0.237352,1.1894 0.37505,2.4243 0.37505,3.6877 0,10.5297 -8.472136,19.0012 -19.0025253,19.0012 -1.1524432,0 -2.2839735,-0.1138 -3.3754486,-0.3124 -0.3421355,-1.7316 -0.5470827,-3.6156 -0.5938289,-5.5317 1.2582172,0.3783 2.5930946,0.5938 3.9692775,0.5938 7.6975233,0 14.0018603,-6.3039 14.0018603,-14.001 0,-1.3726 -0.215038,-2.7139 -0.593829,-3.9689 z m -6.25083,0.3751 c 0.541302,1.0775 0.843862,2.289 0.843862,3.5938 0,4.4542 -3.546611,8.0006 -8.0010633,8.0006 -1.3005129,0 -2.5159044,-0.309 -3.5942277,-0.8437 C 6.9215398,13.8511 7.9452458,10.9911 9.4670181,9.4695 10.98879,7.9478 13.84903,6.9271 17.15554,6.4068 z m 17.814867,2.5938 c 0.199697,0.1561 0.394233,0.3005 0.562575,0.4689 4.611573,4.6112 4.611573,21.4528 0,26.0641 -4.611573,4.6113 -21.454391,4.6113 -26.0659639,0 -0.092912,-0.093 -0.1608714,-0.2099 -0.2500333,-0.3124 0.2618648,0.01 0.5176488,0.031 0.7813539,0.031 13.7734503,0 25.0033223,-11.2291 25.0033223,-25.0016 0,-0.4225 -0.0116,-0.8319 -0.0312,-1.2501 z" style="fill:#ffffff;fill-opacity:1;stroke:none" /></svg>
		Silex
		<span class="subtitle">Installation</span>
	</header>
<?php if($error): ?>
	<div class="error"><?php echo $error ?></div>
<?php endif ?>
	<div class="content">
	<?php if(!$success): ?>
		<form method="post">
			<h1>Database information</h1>
			<table>
				<tr>
					<td><label for="type">Type</label></td>
					<td colspan="2">
						<select name="type" id="type" required>
							<option value="mysql" selected>MySQL</option>
						</select>
					</td>
				</tr>
				<tr>
					<td><label for="host">Host</label>, <label for="port">Port</label></td>
					<td><input type="text" name="host" id="host" value="localhost"></td>
					<td><input type="number" name="port" id="port" min="1" value="3306"></td>
				</tr>
				<tr>
					<td><label for="database">Database</label></td>
					<td colspan="2"><input type="text" name="database" id="database" value="silex" autofocus required></td>
				</tr>
				<tr>
					<td><label for="user">User</label></td>
					<td colspan="2"><input type="text" name="user" id="user" value="root" required></td>
				</tr>
				<tr>
					<td><label for="password">Password</label></td>
					<td colspan="2"><input type="password" name="password" id="password"></td>
				</tr>
			</table>
			<small><b>For now:</b> nothing more to set.</small>
			<input type="submit" name="install" value="Install">
		</form>
	<?php else: ?>
		<h1><?php echo $success ?></h1>
	<?php endif ?>
	</div>
	<footer>
		© 2014 SilexLab
	</footer>
</body>
</html>
