<?php
// This file will be generated as "config.inc.php" by the future Silex installer
// But for now you can copy/rename this file and change the following stuff by hand
return [
'database.host'     => 'localhost',
'database.user'     => 'root',
'database.password' => '',
'database.name'     => 'silex',
'database.port'     => 3306,
'database.wrapper'  => 'mysql',
'password.salt'     => '!f~)pzhtU=&=GtVV7Y&u4wp=3A2xB*_,' // will be randomly generated by the installer
];
